In [ ]:
# Series :

In [9]:
import numpy as np
import pandas as pd

# creating an series with ARRAY

data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)

# creating a series with dict

d = {'asma' : 158, 'parveen' : 159}
s = pd.Series(d)
print(d)

# creating series with scalar values

s = (1,2,3,4,5)
indexx = list('abcde')

d = pd.Series(s, index = indexx)
print(d)

0    a
1    b
2    c
3    d
dtype: object
{'asma': 158, 'parveen': 159}
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [24]:
# Indexing 

# Based on position

a = np.arange(5)
index = list('abcde')
s = pd.Series(a,index = index)
print(s)

print(s[:3]) # retrieves first 3 eles

print('------\n')

# Based on Label

print(s['e'])

# Fancy Indexing : It allows to use an array of indices to access multiple ele's at once

print(s[['a','b']])

a    0
b    1
c    2
d    3
e    4
dtype: int32
a    0
b    1
c    2
dtype: int32
------

4
a    0
b    1
dtype: int32

In [33]:
# Slicing : 

# Normal Slicing

print(s)
print(s[:-2]) # s[i:j-1]

#using label

print(s['a':'d']) # if we use labelled indexing it considers last one also in the output

a    0
b    1
c    2
d    3
e    4
dtype: int32
a    0
b    1
c    2
dtype: int32
a    0
b    1
c    2
d    3
dtype: int32

In [52]:
# Attributes
 
''' 
dtype
ndim
size
name
hasnans
index
empty

'''

fruits = np.array(['apple','mango','orange','grapes'])
indexx = list('abcd')
s = pd.Series(fruits, index = indexx, name = "FRUITS")
print(s)

print(s.dtype)
print(s.ndim)
print(s.size)
print(s.empty)
print(s.index)
print(s.name)
print(s.hasnans) # returns True or False if Nan is present
print(s.values,'\n')


# Methods

print(s.head(2))
print(s.tail(2))

print(s.count())

a     apple
b     mango
c    orange
d    grapes
Name: FRUITS, dtype: object
object
1
4
False
Index(['a', 'b', 'c', 'd'], dtype='object')
FRUITS
False
['apple' 'mango' 'orange' 'grapes']

a    apple
b    mango
Name: FRUITS, dtype: object
c    orange
d    grapes
Name: FRUITS, dtype: object
4

In [60]:
# Mathematical operations on Series

''' 
The values with same indices are added otherwise return NaN
'''
s1= pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([10,20,-10,-50,100],index = ['z', 'y', 'a', 'c', 'e'])

# Addition of two Series
print("The series are: ",s1,s2)
print(s1+s2)
print("------\n")
print(s1.add(s2,fill_value = 0)) 
print(s1.subtract(s2,fill_value = 0))
print(s1.multiply(s2,fill_value = 0))
print(s1.div(s2,fill_value = 0))

The series are:  a    1
b    2
c    3
d    4
e    5
dtype: int64 z     10
y     20
a    -10
c    -50
e    100
dtype: int64
a     -9.0
b      NaN
c    -47.0
d      NaN
e    105.0
y      NaN
z      NaN
dtype: float64
------

a     -9.0
b      2.0
c    -47.0
d      4.0
e    105.0
y     20.0
z     10.0
dtype: float64
a    11.0
b     2.0
c    53.0
d     4.0
e   -95.0
y   -20.0
z   -10.0
dtype: float64
a    -10.0
b      0.0
c   -150.0
d      0.0
e    500.0
y      0.0
z      0.0
dtype: float64
a   -0.10
b     inf
c   -0.06
d     inf
e    0.05
y    0.00
z    0.00
dtype: float64

In [72]:
# String methods

indexx = list('abcd')
a = pd.Series(['aSma','parvEen','nourIn','omarie'],dtype="string")
print(a)

print("-------\n")
print(a.str.upper())
print(a.str.lower())
print(a.str.len())

print("-------\n")

idx=pd.Index(["  jack","jill   ","jesse   ","   frank"])
print(idx)
print(idx.str.rstrip())
print("-----")
print(idx.str.lstrip())
print("\n\n")
idx=pd.Index(["  jack  ","  jill   ","jesse","  frank"])
print(idx)
print(idx.str.strip())

0       aSma
1    parvEen
2     nourIn
3     omarie
dtype: string
-------

0       ASMA
1    PARVEEN
2     NOURIN
3     OMARIE
dtype: string
0       asma
1    parveen
2     nourin
3     omarie
dtype: string
0    4
1    7
2    6
3    6
dtype: Int64
-------

Index(['  jack', 'jill   ', 'jesse   ', '   frank'], dtype='object')
Index(['  jack', 'jill', 'jesse', '   frank'], dtype='object')
-----
Index(['jack', 'jill   ', 'jesse   ', 'frank'], dtype='object')



Index(['  jack  ', '  jill   ', 'jesse', '  frank'], dtype='object')
Index(['jack', 'jill', 'jesse', 'frank'], dtype='object')